# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
sudo: true
dist: trusty
jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk10
  - openjdk11
before_install:
  - chmod +x mvnw
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  - CODECOV_TOKEN="9264fc49-7e36-478e-8930-7245d688220e"

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - alexmur07@mail.ru
    on_success: never # default: change
    on_failure: always # default: always
