# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - oraclejdk11
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  - CODECOV_TOKEN="9264fc49-7e36-478e-8930-7245d688220e"
# Отправлять уведомление на почту alexmur07@mail.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - alexmur07@mail.ru
    on_success: never # default: change
    on_failure: always # default: always
